# Welcome to Jekyll!

title: 魔术师夜光
email: yizhimoshushi@outlook.com
description: >-
  一个不会魔术的魔术师。
baseurl: ""
url: "https://yizhimoshushi.github.io"
github_username: yizhimoshushi

# 这里是关键！换主题的核心配置
plugins:
  - jekyll-feed
  - jekyll-remote-theme # 必须添加这个插件

# 远程主题配置（Cayman 是深海风格）
#remote_theme: pages-themes/cayman
theme: jekyll-theme-cayman

# Cayman 主题的专属配置（让它更好看）
colors:
  primary: "#008489" # 青绿色
  secondary: "#2096ff" # 亮蓝色
  accent: "#db2777" # 粉色点缀
  text: "#333333"
  code: "#333"
  background: "#ffffff"

# 常规设置
timezone: Asia/Shanghai
locale: zh-CN
copyright: "Copyright (c) 2026 魔术师夜光. All rights reserved."
location: "Hainan, China"